blog_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'blog_app'

urlpatterns = [
    path('', views.blog_home, name = 'blog_home' ),
    path('<int:blog_id>', views.blog_details, name = 'blog_details'),
]

portfolioProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home' ),
    path('blog/', include('blog_app.urls'), name = 'blog_home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date = models.DateField()

portfolio_app/models.py
from django.db import models

class Projects(models.Model):
    title = models.CharField(max_length = 50)
    description = models.TextField(max_length = 200)
    image = models.ImageField(upload_to = 'postfolio_app/images')
    url =   models.URLField(blank=True)

blog_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def blog_home(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog_app/blog_home.html', {'blogs': blogs})

def blog_details(request, blog_id):
    blog_detail = get_object_or_404(Blog, pk = blog_id)
    return render(request, 'blog_app/blog_details.html', {'blog':blog_detail})

portfolio_app/views.py
from django.shortcuts import render
from .models import Projects

def home(request):
    projects = Projects.objects.all()
    return render(request, 'portfolio_app/home.html', {'projects': projects}) 

blog_app/templates/blog_app/blog_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Detail</title>
</head>
<body>
    <h1>{{blog.title}}</h1>
    <br>
    <h2>{{blog.date}}</h2>
    <br>
    <p>{{blog.content}}</p>
</body>
</html>

blog_app/templates/blog_app/blog_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <title>Blog</title>
</head>
<body>
    <div class="container text-center">
        <h1>Hello there</h1>
        {% for blog in blogs %}
        <a href="{% url 'blog_app:blog_details' blog.id %}"><h2>{{blog.title}}</h2></a> 
        <h3>{{blog.date}}</h3>
        <p>{{blog.content}}</p>
        {% endfor %}

    </div>
</body>
</html>

portfolio_app/templates/portfolio_app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    <title>Portfolio</title>
</head>
<body>
    <div class="container text-center">
        
        <a href="{% url 'blog_app:blog_home' %}"> <strong>Blog</strong></a> <!-- takes you to the blog_home page -->
        <br> 
        <h1>This is My Portfolio Website</h1>
        {% for project in projects %}
        <h2>{{project.title}}</h2>
        <p>{{project.description}}</p>
        <img src="{{ project.image.url}}" height="160" width="180">
        {% endfor %}
    </div>
</body>
</html>